# Generated by Django 4.1.5 on 2023-06-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
