# Generated by Django 4.1.5 on 2023-06-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_quiz_delete_quizz_delete_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
