# Generated by Django 4.1.5 on 2023-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='time_needed',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
