# Generated by Django 4.1.5 on 2023-06-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_remove_quiz_quiz_id_course_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('quiz_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(default=0),
        ),
    ]
