# Generated by Django 4.1.5 on 2023-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_quiz_details_remove_quiz_quiz_name_quiz_quiz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('video_title', models.CharField(max_length=100)),
                ('Video_description', models.TextField()),
                ('file', models.FileField(upload_to='videos/%y')),
            ],
        ),
    ]
