# Generated by Django 4.1.5 on 2023-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Video_description',
            field=models.CharField(max_length=500),
        ),
    ]
