# Generated by Django 4.1.5 on 2023-06-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0016_alter_video_video_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
