# Generated by Django 4.1.5 on 2023-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0017_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('video_title', models.CharField(max_length=100)),
                ('video_description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='videos/%y')),
            ],
        ),
    ]
