# Generated by Django 4.1.5 on 2023-06-20 07:23

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0018_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='marks',
            field=djongo.models.fields.JSONField(default=None),
        ),
    ]
