# Generated by Django 4.1.5 on 2023-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0019_course_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
