# Generated by Django 4.1.5 on 2023-06-22 05:27

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0020_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='quiz_details',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='quiz_details',
            name='marks',
            field=djongo.models.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='course_enrolled',
            field=djongo.models.fields.JSONField(default=None),
        ),
    ]
