# Generated by Django 4.1.5 on 2023-06-24 12:41

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
        ('instructor', '0023_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.CASCADE, to='authent.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
