# Generated by Django 4.1.5 on 2023-06-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0026_remove_course_enrolled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserX',
        ),
    ]
