# Generated by Django 4.1.5 on 2023-06-29 12:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0028_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=djongo.models.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='course_enrolled',
            field=djongo.models.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
