# Generated by Django 4.1.3 on 2023-07-01 05:02

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0031_remove_course_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.CASCADE, to='instructor.user'),
        ),
    ]
