# Generated by Django 4.1.3 on 2023-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0032_course_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
