# Generated by Django 4.1.3 on 2023-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0033_course_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
