# Generated by Django 4.1.3 on 2023-07-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0034_quiz_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_details',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='quiz_details',
            name='time',
        ),
    ]
