# Generated by Django 4.1.3 on 2023-07-04 09:28

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0035_remove_quiz_details_marks_remove_quiz_details_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled_courses',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        ),
    ]
