# Generated by Django 4.1.5 on 2023-07-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0036_user_enrolled_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course_id', models.IntegerField()),
                ('is_TA', models.BooleanField(default=False)),
            ],
        ),
    ]
