# Generated by Django 4.1.3 on 2023-07-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0037_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
