# Generated by Django 4.1.3 on 2023-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0040_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rated',
            field=models.IntegerField(default=0),
        ),
    ]
