# Generated by Django 4.1.5 on 2023-07-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0041_course_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
