# Generated by Django 4.1.5 on 2023-07-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0042_course_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.ImageField(default=None, upload_to='QR/'),
        ),
    ]
