# Generated by Django 4.1.5 on 2023-07-17 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0044_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_of_pay',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
