# Generated by Django 4.1.3 on 2023-07-28 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0045_payment_date_of_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
