# Generated by Django 4.1.3 on 2023-07-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0046_course_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='uid',
        ),
    ]
