# Generated by Django 4.1.5 on 2023-06-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anouncement',
        ),
    ]
