# Generated by Django 4.1.5 on 2023-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_doubt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doubt',
        ),
    ]
