# Generated by Django 4.1.5 on 2023-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_doubt_replied_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt_ask',
            name='doubt',
            field=models.TextField(default=None),
        ),
    ]
