# Generated by Django 4.1.5 on 2023-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0012_feedback_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('student', models.IntegerField()),
                ('text', models.TextField()),
                ('is_viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
