# Generated by Django 4.1.5 on 2023-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0013_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='urls',
            field=models.URLField(default=None),
        ),
    ]
