# Generated by Django 4.1.5 on 2023-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0014_anouncement_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='star',
            field=models.IntegerField(default=None),
        ),
    ]
