# Generated by Django 4.1.3 on 2023-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0015_feedback_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
